services:
  - type: web
    name: nora-discord-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_COOKIE
        sync: false
      - key: YOUTUBE_DL_SKIP_PYTHON_CHECK
        value: "1"
      - key: NODE_ENV
        value: production

